# # demuxer config not necessary starting with mpv 0.40.0
# demuxer-lavf-o=extension_picky=0
# ytdl-format=bestvideo[height<=?720][fps<=?30][vcodec!=?vp9]+bestaudio/best
#
# [pyradio]
# volume=50
#
#
# Fix color handling in fullscreen
vo=gpu-next

# needed to make fullscreen switch work
target-colorspace-hint=no

# Hardware decoding - essential for CPU offload
hwdec=auto
# Force MPV to use yt-dlp for all URLs that yt-dlp supports
ytdl=yes
ytdl-format=bestvideo[height<=?720][fps<=?30]+bestaudio/best

volume=70

[pyradio]
volume=50
